version: "2"

services:
  nginx:
    build: ./nginx
    image: letsencrypt-docker-compose/nginx
    env_file:
      - ./config.env
    volumes:
      - ./data/etc/nginx/sites:/etc/nginx/sites:ro
      - ./data/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - certbot_acme_challenge:/var/www/certbot:ro
      - site_certs:/etc/nginx/site_certs:ro
      - global_certs:/etc/nginx/global_certs:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  certbot:
    build: ./certbot
    image: letsencrypt-docker-compose/certbot
    env_file:
      - ./config.env
    volumes:
      - certbot_acme_challenge:/var/www/certbot
      - letsencrypt_certs:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workdir:ro
    restart: unless-stopped

  cron:
    build: ./cron
    image: letsencrypt-docker-compose/cron
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workdir:ro
    restart: unless-stopped

volumes:
  certbot_acme_challenge:
  site_certs:
    external: true
  letsencrypt_certs:
    external: true
  global_certs:
    external: true
